version: "3.8"

services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: "demo"

  demo-game-bk:
    image: my-demo-game-image:master
    container_name: my-demo-game
    ports:
      - 3001:3001
    depends_on:
      - mongo
